<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>
<xsl:template match="addressBook">Name,Given Name,Additional Name,Family Name,Yomi Name,Given Name Yomi,Additional Name Yomi,Family Name Yomi,Name Prefix,Name Suffix,Initials,Nickname,Short Name,Maiden Name,Birthday,Gender,Location,Billing Information,Directory Server,Mileage,Occupation,Hobby,Sensitivity,Priority,Subject,Notes,Group Membership,E-mail 1 - Type,E-mail 1 - Value,E-mail 2 - Type,E-mail 2 - Value,E-mail 3 - Type,E-mail 3 - Value,IM 1 - Type,IM 1 - Service,IM 1 - Value,Phone 1 - Type,Phone 1 - Value,Phone 2 - Type,Phone 2 - Value,Phone 3 - Type,Phone 3 - Value,Phone 4 - Type,Phone 4 - Value,Address 1 - Type,Address 1 - Formatted,Address 1 - Street,Address 1 - City,Address 1 - PO Box,Address 1 - Region,Address 1 - Postal Code,Address 1 - Country,Address 1 - Extended Address,Address 2 - Type,Address 2 - Formatted,Address 2 - Street,Address 2 - City,Address 2 - PO Box,Address 2 - Region,Address 2 - Postal Code,Address 2 - Country,Address 2 - Extended Address,Organization 1 - Type,Organization 1 - Name,Organization 1 - Yomi Name,Organization 1 - Title,Organization 1 - Department,Organization 1 - Symbol,Organization 1 - Location,Organization 1 - Job Description,Website 1 - Type,Website 1 - Value,Website 2 - Type,Website 2 - Value
<xsl:apply-templates select="contact" />
</xsl:template>
<xsl:template match="contact">"<xsl:value-of select="fullName"/>","<xsl:value-of select="firstName"/>","<xsl:value-of select="middleName"/>","<xsl:value-of select="lastName"/>",,,,,"<xsl:value-of select="prefix"/>","<xsl:value-of select="suffix"/>",,"<xsl:value-of select="nickName"/>",,,"<xsl:value-of select="substring-before(birthday,' ')"/>",,,,,,,,,,,"<xsl:value-of select="Notes"/>","<xsl:value-of select="categories"/>","*","<xsl:value-of select="email"/>",,"<xsl:value-of select="email2"/>",,"<xsl:value-of select="email3"/>",,,"<xsl:value-of select="IMAddress"/>","Work","<xsl:value-of select="busPhone"/>","Home","<xsl:value-of select="homePhone"/>","Work Fax","<xsl:value-of select="busFax"/>","Home Fax","<xsl:value-of select="homeFax"/>",<xsl:choose><xsl:when test="busAddress">"Work","<xsl:value-of select="busAddress"/><xsl:text>
</xsl:text><xsl:value-of select="busCity"/>, <xsl:value-of select="busState"/><xsl:text>  </xsl:text><xsl:value-of select="busZipCode"/>","<xsl:value-of select="busAddress"/>","<xsl:value-of select="busCity"/>",,,"<xsl:value-of select="busZipCode"/>","<xsl:value-of select="busCountry"/>",,</xsl:when><xsl:otherwise>,,,,,,,,,</xsl:otherwise></xsl:choose><xsl:choose><xsl:when test="homeAddress">"Home","<xsl:value-of select="homeAddress"/><xsl:text>
</xsl:text><xsl:value-of select="homeCity"/>, <xsl:value-of select="homeState"/><xsl:text>  </xsl:text><xsl:value-of select="homeZipcode"/>","<xsl:value-of select="homeAddress"/>","<xsl:value-of select="homeCity"/>",,,"<xsl:value-of select="homeZipcode"/>","<xsl:value-of select="homeCountry"/>",,</xsl:when><xsl:otherwise>,,,,,,,,,</xsl:otherwise></xsl:choose>,"<xsl:value-of select="busCompany"/>",,"<xsl:value-of select="busTitle"/>","<xsl:value-of select="busDepartment"/>",,,,"Work","<xsl:value-of select="busWebAddress"/>","Home","<xsl:value-of select="homeWebAddress"/>"
</xsl:template>
</xsl:stylesheet>
